[window]
option_as_alt = "Both"

[font.normal]
family = "FiraCode Nerd Font"

[general]
import = [
  "~/.config/alacritty/themes/catppuccin.toml"
]

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "H", mods = "Control|Shift", mode = "~Vi", action = "ToggleViMode" },
  { key = "H", mods = "Control|Shift", mode = "Vi", action = "ToggleViMode" }
]

# [terminal]
#
# [terminal.shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "$HOME/.config/alacritty/start.sh"]
